CREATE_USERS_TABLE = """
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    telegram_id INTEGER UNIQUE NOT NULL,
    username TEXT,
    timezone TEXT NOT NULL DEFAULT 'UTC+3',
    registered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
"""

CREATE_MEETINGS_TABLE = """
CREATE TABLE IF NOT EXISTS meetings (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    creator_id INTEGER NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    finalized_option_id INTEGER DEFAULT NULL,
    FOREIGN KEY (creator_id) REFERENCES users (id) ON DELETE CASCADE
);
"""

CREATE_MEETING_OPTIONS_TABLE = """
CREATE TABLE IF NOT EXISTS meeting_options (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    meeting_id INTEGER NOT NULL,
    option_datetime TEXT NOT NULL,
    option_text TEXT NOT NULL,
    FOREIGN KEY (meeting_id) REFERENCES meetings (id) ON DELETE CASCADE
);
"""

CREATE_PARTICIPANTS_TABLE = """
CREATE TABLE IF NOT EXISTS participants (
    meeting_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (meeting_id, user_id),
    FOREIGN KEY (meeting_id) REFERENCES meetings (id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
"""

CREATE_VOTES_TABLE = """
CREATE TABLE IF NOT EXISTS votes (
    option_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    voted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (option_id, user_id),
    FOREIGN KEY (option_id) REFERENCES meeting_options (id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
"""

CREATE_REMINDERS_TABLE = """
CREATE TABLE IF NOT EXISTS reminders (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    meeting_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    reminder_minutes INTEGER NOT NULL,
    is_sent BOOLEAN DEFAULT 0,
    FOREIGN KEY (meeting_id) REFERENCES meetings (id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
"""

TABLES = [
    CREATE_USERS_TABLE,
    CREATE_MEETINGS_TABLE,
    CREATE_MEETING_OPTIONS_TABLE,
    CREATE_PARTICIPANTS_TABLE,
    CREATE_VOTES_TABLE,
    CREATE_REMINDERS_TABLE,
]